Models/GradeCalculatorModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace FixedFirstWebApp.Models
{
    public class GradeCalculatorModel
    {
        [Required]
        [Range(0, 100, ErrorMessage = "Please enter a number between 0 and 100")]
        public double Assignment { get; set; }

        [Range(0, 100, ErrorMessage = "Please enter a number between 0 and 100")]
        public double GroupProject { get; set; }

        [Range(0, 100, ErrorMessage = "Please enter a number between 0 and 100")]
        public double Quiz { get; set; }

        [Range(0, 100, ErrorMessage = "Please enter a number between 0 and 100")]
        public double Exam { get; set; }

        [Range(0, 100, ErrorMessage = "Please enter a number between 0 and 100")]
        public double Intex { get; set; }

    }
}

Controllers/BaseController.cs
using Microsoft.AspNetCore.Mvc;
using FixedFirstWebApp.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FixedFirstWebApp.Controllers
{
    public class BaseController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet("GradeCalculator")]
        public IActionResult GradeCalculator()
        {
            return View();
        }

        [HttpPost("GradeCalculator")]
        public IActionResult GradeCalculator(GradeCalculatorModel model)
        {
            return View();
        }

    }
}

Views/Base/GradeCalculator.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewBag.Title = "Grade Calculator";
}

@model FixedFirstWebApp.Models.GradeCalculatorModel

<body>
    <h2>Grade Calculator</h2>
    <div class="card">
        <p class="picDescrip">Please input the percent you received of each category below: </p>
        <form method="post">
            <label>Assignments:</label>
            <input id="Assignment" asp-for="Assignment" />
            <br />
            <label>Group Project: </label>
            <input id="GroupProject" asp-for="GroupProject" />
            <br />
            <label>Quizzes: </label>
            <input id="Quiz" asp-for="Quiz" />
            <br />
            <label>Exams: </label>
            <input id="Exam" asp-for="Exam"/>
            <br />
            <label>Intex: </label>
            <input id="Intex" asp-for="Intex"/>
            <br />
            <br />
            <input type="submit" value="Calculate" id="submitButton" />
            <div asp-validation-summary="All"></div>
        </form>
        <!-- This is where the grade message will be populated by the javascript when the submit button is pressed -->
        <p id="gradeMessage"></p>
    </div>
</body>

Views/Base/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewBag.Title = "Home";
}


<body>
    <h2 class="sectionTitle">What I do for fun</h2>
    <div class="card">
        <img class="funPic" src="~/img/meemmafair.jpg" />
        <p class="picDescrip">
            Pictured above is my girlfriend and I at the Utah State Fair
            (because my main hobby (for better or worse) is doing things with my girlfriend.)
        </p>
    </div>

    <h2>What I hope to get out of IS 413</h2>
    <div class="card">
        <p>
            I hope to gain extensive knowledge of this framework because of its wide use in industry.
            I want to be able to utilize these skills at the end of the semester with industry-level
            proficiency. I also hope this will make me better equipped to deal with all types of languages
            and frameworks, and I love that I will be able to add another programming language to my skills
            bank.
        </p>
    </div>

    <h2>Top Three Jobs</h2>
    <div class="card">
        <ol>
            <li>Data Analyst</li>
            <li>Software Developer</li>
            <li>Tech Entrepreneur</li>
        </ol>
    </div>
</body>

Views/Shared/_Layout.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
  
}

<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title</title>
    <link href="~/css/StyleSheet.css" rel="stylesheet" />
    <link rel="shortcut icon" href="img/Account.ico" />
</head>

<body>
    <header>
        <h1>@ViewBag.Title</h1>
        <a asp-controller="Base" asp-action="Index">Home</a>
        <br />
        <a asp-controller="Base" asp-action="GradeCalculator">Grade Calculator</a>
    </header>
    <div class="main">

    @RenderBody()

    </div>
    <footer>
        <div class="container">
            <br />
            <div>©2021 Ryan's Profile</div>
        </div>
    </footer>
    <script src="~/node_modules/jquery/dist/jquery.min.js"></script>
    <script src="~/js/gradeCalc.js"></script>
</body>

</html>